### ISSUE TITLE
Merge meteor branch

### ISSUE THREAD

**Issue by brishin** [adicu/Courses#165]
Deliverables:
- [x] Backport 90% of features
- [x] Schedule saving with short URL
- [x] #161 (External week view code)
- [x] Basic unit test and integration testing
- [x] ~~Continuous integration (with Docker/Travis)~~
- [x] Basic documentation of routing, template, controller code (update README)
- [x] Proper import scripts for DB, ~~Elasticsearch~~
- [x] Port to Javascript

Should address:
- [x] #171 
- [x] #151 
- [x] #134 (Move to meteor build system)
- [x] #133 
- [x] #119 (Create per schedule URL)
- [x] #115 
- [x] #110 (Allow courses with no sections gracefully)
- [x] #80 (Build this UI out)
- [x] #78 (Implemented by iron router)
- [x] #73 (Close - wontfix)

**Comment by brishin** [comment]
@natebrennand Let me know if you have items to add.

**Comment by natebrennand** [comment]
long discussion on Coffeescript vs JS may necessitate another point

**Comment by brishin** [comment]
Infra breakout?
One nice thing about meteor is that Coffeescript is automatically compiled and watched so we're rid of that giant `Gruntfile`

**Comment by natebrennand** [comment]
We'll discuss during infra but the Gruntfile has not been the bottleneck
RE: coffeescript

**Comment by brishin** [comment]
Making great progress! :smile_cat: 
![screen shot 2014-04-14 at 17 42 15](https://cloud.githubusercontent.com/assets/920130/2701180/c8704f56-c41d-11e3-9f0f-370931ba6daf.png)

**Comment by brishin** [comment]
A basic version up at http://courses.meteor.com/schedule
